-- Flyway baseline schema (no extension, UUID generated by app)

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
    id UUID PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id UUID NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS projects (
    id UUID PRIMARY KEY,
    code VARCHAR(50),
    name VARCHAR(300) NOT NULL,
    plan_year INT,
    status VARCHAR(50),
    start_date DATE,
    end_date DATE,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS packages (
    id UUID PRIMARY KEY,
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    name VARCHAR(300) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS contracts (
    id UUID PRIMARY KEY,
    package_id UUID NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
    number VARCHAR(100),
    signed_date DATE,
    effective_date DATE,
    duration_months INT,
    expire_date DATE,
    value BIGINT,
    currency VARCHAR(10),
    bidder_name VARCHAR(300),
    type VARCHAR(50),
    payment_installments INT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payments (
    id UUID PRIMARY KEY,
    contract_id UUID NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
    installment_no INT NOT NULL,
    planned_pay_date DATE,
    planned_amount BIGINT,
    actual_pay_date DATE,
    actual_amount BIGINT,
    status VARCHAR(20) NOT NULL,
    voucher_no VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY,
    project_id UUID NULL REFERENCES projects(id) ON DELETE CASCADE,
    package_id UUID NULL REFERENCES packages(id) ON DELETE CASCADE,
    contract_id UUID NULL REFERENCES contracts(id) ON DELETE CASCADE,
    payment_id UUID NULL REFERENCES payments(id) ON DELETE CASCADE,
    type VARCHAR(50),
    name VARCHAR(300) NOT NULL,
    path TEXT NOT NULL,
    size BIGINT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID PRIMARY KEY,
    user_id UUID NULL,
    action VARCHAR(100) NOT NULL,
    entity VARCHAR(100),
    entity_id UUID NULL,
    detail TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_projects_plan_year ON projects(plan_year);
CREATE INDEX IF NOT EXISTS idx_projects_status ON projects(status);
CREATE INDEX IF NOT EXISTS idx_packages_project_id ON packages(project_id);
CREATE INDEX IF NOT EXISTS idx_contracts_package_id ON contracts(package_id);
CREATE INDEX IF NOT EXISTS idx_documents_project_id ON documents(project_id);
CREATE INDEX IF NOT EXISTS idx_documents_package_id ON documents(package_id);
CREATE INDEX IF NOT EXISTS idx_documents_contract_id ON documents(contract_id);
